name: Build and push Docker image to Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - name: Build node artifact
        run: yarn build
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: notclive
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: notclive/zero-interaction-oidc-provider:latest
