name: Build and push Docker image to Docker Hub

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - name: Check types
        run: yarn typecheck
      - name: Build node artifact
        run: yarn build
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: notclive/zero-interaction-oidc-provider
          tags: type=ref,event=tag
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: notclive
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push the Docker image
        uses: docker/build-push-action@v2
        with:
          context: build
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
