name: Run automated tests

on: [ push ]

jobs:
  run-cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - name: Check types
        run: yarn typecheck
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: test
          build: yarn
          start: yarn test